GET http://localhost:3000/comments/ HTTP/1.1

###

POST http://localhost:3000/comments/ HTTP/1.1
content-Type: application/json

{
    "text": "a thrid comment",
    "likes": 0,
    "userId": "661958a291b0a638556df89d"
}

###

GET http://localhost:3000/comments?parentId=66196313821aa87c1444f70c/ HTTP/1.1

###
